### ISSUE TITLE
Allow Executing Callbacks on Non-URL Parts

### ISSUE THREAD

**Issue by ragurney** [mobilusoss/react-anchorify-text#23]
Hi, 

I'm using this as part of a series of parsing treatments to strings that I need to chain together, e.g.
```
string = 'Hello I am https://google.com a special string'
... // string treatments
string is now: <span>Hello I am <a href='https://google.com'>https://google.com</a> a <span class='special'>special</span> string</span>
```
I was wondering if, to facilitate this, `AnchorifyText` could take in an optional prop which would be a function executed on all non-match strings. This way I could chain the two parsers together to achieve a result like the one above. Would that be possible?

**Comment by georgeOsdDev** [comment]
Currently there is no option to resolve your issue.

I think it will be possible to add props like `nonUrlPartsRenderer: (nonUrlText) => {}`
And apply this in 
https://github.com/mobilusoss/react-anchorify-text/blob/master/src/components/AnchorifyText.js#L29

We are welcome your PR.
